id = "glow"
description = "render markdown on the CLI"
profiles = ["extended"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_release"
repo = "charmbracelet/glow"

[strategy]
type = "archive_extract"

[strategy.match]
x86_64 = '(?i)^glow_.*_Linux_x86_64\.tar\.gz$'
arm64 = '(?i)^glow_.*_Linux_arm64\.tar\.gz$'

[strategy.extract]
include = ["glow"]
target_dir = "bin"
