id = "lazygit"
description = "simple terminal UI for git commands"
profiles = ["extended"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_release"
repo = "jesseduffield/lazygit"

[strategy]
type = "archive_extract"

[strategy.match]
x86_64 = '(?i)^lazygit_.*_Linux_x86_64\.tar\.gz$'
arm64 = '(?i)^lazygit_.*_Linux_arm64\.tar\.gz$'

[strategy.extract]
include = ["lazygit"]
target_dir = "bin"
