id = "yazi"
description = "terminal file manager"
profiles = ["extended"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_release"
repo = "sxyazi/yazi"

[strategy]
type = "archive_extract"

[strategy.match]
x86_64 = '(?i)^yazi-x86_64-unknown-linux-musl\.zip$'
arm64 = '(?i)^yazi-aarch64-unknown-linux-musl\.zip$'

[strategy.extract]
include = ["ya", "yazi"]
target_dir = "bin"
