id = "zimfw"
description = "offline zimfw runtime"
profiles = ["extended"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_release"
repo = "zimfw/zimfw"

[strategy]
type = "direct_binary"

[strategy.match]
x86_64 = '(?i)^zimfw\.zsh$'
arm64 = '(?i)^zimfw\.zsh$'

[strategy.extract]
target_dir = "cache/zim"
target_name = "zimfw.zsh"
