id = "zimfw-zsh-autosuggestions"
description = "zsh autosuggestions module"
profiles = ["extended"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_archive"
repo = "zsh-users/zsh-autosuggestions"
ref = "master"

[strategy]
type = "archive_tree"

[strategy.extract]
target_dir = "cache/zim/modules/zsh-autosuggestions"
strip_components = 1
