id = "zimfw-git"
description = "zimfw git module"
profiles = ["extended"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_archive"
repo = "zimfw/git"
ref = "master"

[strategy]
type = "archive_tree"

[strategy.extract]
target_dir = "cache/zim/modules/git"
strip_components = 1
