id = "zsh"
description = "prebuilt zsh from romkatv/zsh-bin (offline install)"
profiles = ["core"]
architectures = ["x86_64", "arm64"]

[source]
type = "local_file"
repo = "romkatv/zsh-bin"
file_path = "../assets/zsh-bin/zsh-5.8-linux-${ARCH}.tar.gz"

[strategy]
type = "direct_binary"

[strategy.extract]
target_dir = "zsh-bin"
target_name = "zsh-5.8-linux.tar.gz"
