id = "zsh"
description = "prebuilt zsh"
profiles = ["core"]
architectures = ["x86_64", "arm64"]

[source]
type = "github_release"
repo = "romkatv/zsh-bin"

[strategy]
type = "archive_tree"

[strategy.match]
x86_64 = '(?i)^zsh-.*-linux-x86_64\.tar\.gz$'
arm64 = '(?i)^zsh-.*-linux-aarch64\.tar\.gz$'

[strategy.extract]
target_dir = ""
strip_components = 0
