[profiles.core]
packages = ["fzf", "bat", "rg", "fd", "delta", "zsh", "zsh-bin-install-script"]

[profiles.extended]
extends = ["core"]
packages = [
  "aichat",
  "crush",
  "dust",
  "duf",
  "eza",
  "fastfetch",
  "fish",
  "font-jetbrains-maple-mono",
  "forceterm",
  "glow",
  "jq",
  "lazygit",
  "navi",
  "opencode",
  "ouch",
  "ruff",
  "upx",
  "uv",
  "yazi",
  "yq",
  "zellij",
  "zoxide",
  "oh-my-zsh",
  "oh-my-zsh-z",
  "oh-my-zsh-zsh-autosuggestions",
  "oh-my-zsh-zsh-syntax-highlighting",
]

[profiles.experimental]
extends = ["extended"]
packages = []
